name: hyperalign
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - tqdm
  - matplotlib
  - pyyaml
  - pip:
      - --index-url https://pypi.org/simple
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - -f https://data.pyg.org/whl/torch-2.7.0+cu128.html
      - torch==2.7.0
      - torchvision==0.22.0
      - pyg_lib==0.5.0+pt27cu128
      - torch_scatter==2.1.2+pt27cu128
      - torch_sparse==0.6.18+pt27cu128
      - torch_cluster==1.6.3+pt27cu128
      - torch_spline_conv==1.2.2+pt27cu128
      - torch_geometric==2.7.0
      - wandb==0.24.0
      - scikit-learn
      - tensorboardX
      - torch==2.7.0
      - torchvision==0.22.0
      - pyg_lib==0.5.0+pt27cu128
      - torch_scatter==2.1.2+pt27cu128
      - torch_sparse==0.6.18+pt27cu128
      - torch_cluster==1.6.3+pt27cu128
      - torch_spline_conv==1.2.2+pt27cu128
      - torch_geometric==2.7.0
      - wandb==0.24.0
      - scikit-learn
      - tensorboardX
      - rich
