dataset: partnet
root: data_utils/partnet/output/fpfh_rigid
descriptor: fpfh
inlier_threshold: 0.10
downsample: 0.02
re_thre: 15
te_thre: 30
val_ratio: 0.1
use_features: true
feature_dim: 33
neg_ratio: 2.0
seed_ratio: 0.2
num_node: 256
batch_size: 1
num_workers: 4
skip_gt_trans: true
aggregation: wasserstein
